{
 "title": "Data Collection - Error Analysis",
 "time": { "from": "now/y", "to": "now/y" },
 "refresh": "30m",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User Progress",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 1 },
   "targets": [
    { "rawSql": "SELECT * from userprogress" }
   ]
  },
  {
   "title": "Total Participant",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id) from background;"
    }
   ]
  },
  {
   "title": "Task2 Done (ALL DONE)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(task2done)/count(id)*100 from userprogress"
    }
   ]
  },
  {
   "title": "Task1 Done",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(task1done)/count(id)*100 from userprogress"
    }
   ]
  },
  {
   "title": "Background Information",
   "type": "table",
   "gridPos": { "h": 16, "w": 23, "x": 0, "y": 14 },
   "targets": [
    { "rawSql": "SELECT * from background;" }
   ]
  },
  { "title": "Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Native Language Distribution",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "Select language, count(language) from background group by language;"
    }
   ]
  },
  {
   "title": "English Level Distribution",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 38 },
   "targets": [
    {
     "rawSql": "Select english, count(english) from background group by english;"
    }
   ]
  },
  {
   "title": "Korean Level Distribution",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 38 },
   "targets": [
    {
     "rawSql": "Select learningTime, count(learningTime) from background group by learningTime;"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Task 1 Answer",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    { "rawSql": "select * from task1;" }
   ]
  },
  {
   "title": "Task 2 Answer",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    { "rawSql": "select * from task2;" }
   ]
  }
 ]
}